level_five/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

level_five/level_five/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout, name='logout'),
    path('special/',views.special,name='special'),
]

level_five/first_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    # additional
    portfolio_site = models.URLField(blank=True,null=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

level_five/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

level_five/first_app/views.py
from django.shortcuts import render
from first_app.forms import UserForm, UserProfileInfoForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.


def index(request):
    return render(request, 'first_app/index.html')


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        profile_form = UserProfileInfoForm()
        user_form = UserForm()

    return render(request, 'first_app/registration.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print('someone tried to login and failed!')
            print("username: {} and password: {}".format(username, password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'first_app/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("you are logged in, Nice!")

level_five/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'first_app:register' %}" class="nav-link">Register</a>
        </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
                <a href="{% url 'first_app:user_login' %}" class="nav-link">login</a>
            </li>
          {% endif %}

      </ul>
    </div>
  </div>
</nav>
<!--      <a class="navbar-brand" href="{% url 'index' %}">Home</a>-->
<!--        <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>-->
<!--          <a href="{% url 'first_app:register' %}" class="nav-link">Register</a>-->
    <div class="container">
                {% block body_block %}
                {% endblock %}
    </div>
</body>
</html>

level_five/templates/first_app/index.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}

level_five/templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'first_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password: </label>
        <input type="text" name="password">

        <input type="submit" name="" value="Login">
    </form>
</div>
{% endblock %}

level_five/templates/first_app/registration.html
{% extends 'first_app/base.html' %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form: </h3>
    <form enctype="multipart/form-data" method="POST">

        {{ user_form.as_p }}
        {{ profile_form.as_p}}
        {% csrf_token %}
        <input type="submit" name="" value="Register">
    </form>
    {% endif %}
</div>
{% endblock %}